carSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path

from . import views

app_name='cars'


urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.admin1, name='upload'),
]

cars/models.py
from django.db import models

# Create your models here.

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / cars_photos/<filename>
    return '{0}/{1}'.format("cars_photos",filename)


class cars_data(models.Model):
    car_Id = models.AutoField(primary_key=True)
    car_Name = models.CharField(max_length=100, blank=False, null=False )
    Car_Model = models.CharField(max_length=100, blank=False, null=False)
    car_Price = models.IntegerField(max_length=15, blank=False, null=False)
    car_Photo = models.FileField(upload_to=user_directory_path, null=True, verbose_name="")

    class Meta:
        db_table = 'cars' 

cars/views.py
from django.shortcuts import render
from .models import *
from carSite.settings import BASE_DIR
# Create your views here.

def index(request):
    # cars_data.objects.all().delete() #To Delete the data
    cars = cars_data.objects.all()
    return render(request, 'index.html', {'cars':cars, 'BASE_DIR':BASE_DIR})


def admin1(request):
    if request.method == 'POST':
        car = cars_data()
        car.car_Name = request.POST.get("car_name", False)
        car.car_Price = request.POST.get("car_price", False)
        car.Car_Model = request.POST.get("car_model", False)
        car.car_Photo = request.FILES.get("car_photo", False)
        car.save()

    
    return render(request, 'upload.html')

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div style="margin: 150px;">
        <div style="text-align: center; margin-bottom: 20px;">
            <h2>Dev By Mangesh Mahadeo Kokare 22112035</h2>
        </div>
        <a href="{% url 'cars:upload' %}">Upload</a>
        {% for car in cars %}
        <div class="card mb-3">
            <img src="{{ BASIC_DIR }}/uploads/{{car.car_Photo}}" alt="dish_img" class="img-fluid p-2">
            <div class="card-body">
              <h5 class="card-title">{{car.car_Name}}</h5>
              <p class="card-text">{{car.Car_Model}}</p>
              <p class="card-text"><small class="text-muted">{{car.car_Price}}</small></p>
            </div>
          </div>
        {% endfor %}
    </div>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
 
    <div style="margin: 150px;">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              <label for="car_name">Car Name</label>
              <input type="name" class="form-control" name="car_name" id="car_name" aria-describedby="emailHelp" placeholder="Enter Car Name">
            
            </div> <br>

            <div class="form-group">
              <label for="car_model">Car Model</label>
              <input type="text" name="car_model" class="form-control" id="car_model" placeholder="Car Model ?">
            </div> <br>

            <div class="form-group">
                <label for="car_price">Car Price</label>
                <input type="number" name="car_price" class="form-control" id="car_price" placeholder="Price ?">
              </div> <br>

              <div class="form-group">
                <label for="car_photo">Example file input</label>
                <input type="file" class="form-control-file" id="car_photo" name="car_photo">
              </div>

            <button type="submit" class="btn btn-primary">Submit</button>
          </form>  

    </div>




    
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    
</body>
</html>